-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."college_staff" add column "forgot_password_token_hash" text
--  null;
